FROM golang:1.23 AS builder

ENV GO11MODULE=on
    CGO_ENABLED=0
    GOOS=linux

WORKDIR /app


COPY go.mod go.sum ./
RUN go mod download


COPY . .

RUN go build -o main .

FROM gcr.io/distroless/static:nonroot

WORKDIR /

COPY --from=builder /app/main .

EXPOSE 8661

USER nonroot:nonroot

CMD ["./main"]
